/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aisino_taxcode_skm */

#ifndef _Included_com_aisino_taxcode_skm
#define _Included_com_aisino_taxcode_skm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aisino_taxcode_skm
 * Method:    get_dzfp_skm
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aisino_taxcode_skm_get_1dzfp_1skm
  (JNIEnv *, jclass, jstring, jint, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
